In [1]:
def even_odd(num):
    if num%2 == 0:
        print("The number is even")
    else:
        print("The number is odd")
even_odd(13)        

The number is odd


### Print vs Return

In [2]:
def hello_world():
    print("Hello welcome")

hello_world()

Hello welcome


In [3]:
#Return

In [4]:
def hello_world1():
    return "Hello Welcome"


In [5]:
val = hello_world1()

In [6]:
print(val)

Hello Welcome


In [7]:
def add_number(num1,num2):
    print(num1+num2)
    

In [8]:
val = add_number(23,34)

57


In [9]:
val

In [10]:
add_number(12,23)

35


### Positional and keyword arguments

In [31]:
def hello(name,age=26):
    print("My name is {} and my age is {}".format(name,age))

In [32]:
hello("Rohit")

My name is Rohit and my age is 26


In [34]:
def hello(*args,**kwargs):
    print(args)
    print(kwargs)

In [38]:
hello("Rohit", "Jaiswal", age = 26, dob = 1996, doj= 1998) 

('Rohit', 'Jaiswal')
{'age': 26, 'dob': 1996, 'doj': 1998}


In [39]:
lst = ["Rohit", "Jaiswal"]

In [40]:
dict_arrays = {"age":26, "dob": 1996}

In [43]:
hello(*lst, **dict_arrays)

('Rohit', 'Jaiswal')
{'age': 26, 'dob': 1996}


### Lambda Functions

In [46]:
addition = lambda a,b : a+b

In [48]:
addition(10,12)

22

In [62]:
def even(num):
    if num%2==0:
        return True

In [64]:
even(10)

True

In [71]:
even1 = lambda a : a%2==0

In [72]:
even1(12)

True

In [73]:
def addition(x,y,z):
    return x+y+z

In [74]:
addition(12,23,454)

489

In [83]:
addition1 = lambda x : x%2==0

In [85]:
addition1(3)

False

In [88]:
def even(num):
    if num%2==0:
        print("The number is even")
    else:
        print("The number is odd")

In [90]:
even(12)

The number is even


In [99]:
def addition(num1,num2):
    return num1+num2
    if num1+num2>=10:
        print("number is greater than positive number")
    else:
        print("number is not graeter than positive number")
    
        

In [102]:
addition= lambda x,y,z : x+y+z

In [103]:
addition(2,3,4)

9

In [109]:
addition = lambda x : x**5

In [110]:
addition(3)

243

In [111]:
def hello_world(name, age = 23):
    print("My name is {} and my age is {}".format(name,age))

In [112]:
hello_world("Rohit")

My name is Rohit and my age is 23


In [113]:
def integer(num):
    if num%2==0:
        print("The number is positive")
    elif num>=0:
        print("The number is greater than zero")
    else:
        print("The number is unknown")

In [116]:
integer(3)

The number is greater than zero


In [117]:
def integer(num):
    if num%2==0:
        print("The number is even")
    else:
        print("The number is odd")

In [119]:
integer(22)

The number is even


In [120]:
lst = ["Mathemetics", "Physics", "chemistry",12,34,56]

In [121]:
len(lst)

6

In [122]:
lst.append("Rohit")

In [123]:
lst

['Mathemetics', 'Physics', 'chemistry', 12, 34, 56, 'Rohit']

In [127]:
lst = [1,2,3,4,5,6,7,8,9]

In [128]:
lst.append([10,11,12,13])

In [129]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, [10, 11, 12, 13]]

In [130]:
lst.extend([12,13,14])

In [131]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, [10, 11, 12, 13], 12, 13, 14]

In [133]:
lst[12:]

[14]

In [136]:
lst2 = [1,2,3,4,5,6,7,8,9]

In [138]:
lst2.count(1)

1

In [139]:
dict  = {"car1" : "Audi", "car2":"Maruti", "car3": "innova"}

In [140]:
dict["car1"]

'Audi'

In [142]:
dict["car1"]

'Audi'

In [143]:
for i in dict:
    print(i)

car1
car2
car3


In [145]:
for i in dict.values():
    print(i)
    

Audi
Maruti
innova


In [146]:
for i in dict.items():
    print(i)

('car1', 'Audi')
('car2', 'Maruti')
('car3', 'innova')


In [149]:
dict["car4"]= "suzuki"

In [150]:
dict

{'car1': 'Audi', 'car2': 'Maruti', 'car3': 'innova', 'car4': 'suzuki'}

In [151]:
# ARRAY

In [153]:
import numpy as np

In [154]:
arr = np.random.rand(3,3)

In [155]:
arr

array([[0.24881058, 0.12604336, 0.63086811],
       [0.88784226, 0.47962829, 0.92387402],
       [0.37758428, 0.09382555, 0.39408007]])

In [156]:
arr1 = np.random.randn(4,4)

In [157]:
arr1

array([[-0.32295494,  0.22098885,  0.40608079, -1.89727667],
       [ 1.33253235, -2.15590507,  0.85639083,  0.49682329],
       [ 0.71057859, -0.81197073,  0.57222311,  0.64405624],
       [-0.45300523, -0.93568524,  1.23727909, -0.64210858]])

In [171]:
arr2 = np.random.randint(1,100,5)

In [173]:
arr2

array([90, 98, 26, 32, 94])

In [166]:
arr3 = np.arange(1,100,5)

In [167]:
arr3

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [170]:
arr3.size

20

In [183]:
arr4 =  np.random.random_sample((3,5))

In [184]:
arr4

array([[0.44976358, 0.60676883, 0.89912939, 0.8815443 , 0.69550089],
       [0.05291501, 0.57959239, 0.65929677, 0.87482102, 0.37013095],
       [0.49639071, 0.45182699, 0.94461827, 0.41080961, 0.46969339]])